#!/bin/bash
called=${BASH_SOURCE[0]}
if [[ $called != $0 ]]
then
	echo -e "Now entering the churrera underworld!"
	aux=$( realpath $0 )
	export churrerapath=${aux%/$0}/$(dirname $called)
	export PATH=$PATH:$churrerapath/utils
	PS1='\[\033[01;32m\]\u@\[\033[01;33m\]churrera\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
fi

